package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Garantias implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Garantia")
	private java.util.List<com.relative.pruebas.Garantia> Garantia;

	public Garantias() {
	}

	public java.util.List<com.relative.pruebas.Garantia> getGarantia() {
		return this.Garantia;
	}

	public void setGarantia(
			java.util.List<com.relative.pruebas.Garantia> garantia) {
		this.Garantia = garantia;
	}

	public Garantias(java.util.List<com.relative.pruebas.Garantia> garantia) {
		this.Garantia = garantia;
	}

}