package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimularResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "CodigoError")
	private java.lang.String codigoError;
	@org.kie.api.definition.type.Label(value = "Mensaje")
	private java.lang.String mensaje;
	@org.kie.api.definition.type.Label(value = "NumeroOperacionMadre")
	private java.lang.String numeroOperacionMadre;
	@org.kie.api.definition.type.Label(value = "XmlOpcionesRenovacion")
	private com.relative.pruebas.XmlOpcionesRenovacion xmlOpcionesRenovacion;
	@org.kie.api.definition.type.Label(value = "XmlGarantias")
	private com.relative.pruebas.XmlGarantias xmlGarantias;

	public SimularResult() {
	}

	public java.lang.String getCodigoError() {
		return this.codigoError;
	}

	public void setCodigoError(java.lang.String codigoError) {
		this.codigoError = codigoError;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.String getNumeroOperacionMadre() {
		return this.numeroOperacionMadre;
	}

	public void setNumeroOperacionMadre(java.lang.String numeroOperacionMadre) {
		this.numeroOperacionMadre = numeroOperacionMadre;
	}

	public com.relative.pruebas.XmlOpcionesRenovacion getXmlOpcionesRenovacion() {
		return this.xmlOpcionesRenovacion;
	}

	public void setXmlOpcionesRenovacion(
			com.relative.pruebas.XmlOpcionesRenovacion xmlOpcionesRenovacion) {
		this.xmlOpcionesRenovacion = xmlOpcionesRenovacion;
	}

	public com.relative.pruebas.XmlGarantias getXmlGarantias() {
		return this.xmlGarantias;
	}

	public void setXmlGarantias(com.relative.pruebas.XmlGarantias xmlGarantias) {
		this.xmlGarantias = xmlGarantias;
	}

	public SimularResult(java.lang.String codigoError,
			java.lang.String mensaje, java.lang.String numeroOperacionMadre,
			com.relative.pruebas.XmlOpcionesRenovacion xmlOpcionesRenovacion,
			com.relative.pruebas.XmlGarantias xmlGarantias) {
		this.codigoError = codigoError;
		this.mensaje = mensaje;
		this.numeroOperacionMadre = numeroOperacionMadre;
		this.xmlOpcionesRenovacion = xmlOpcionesRenovacion;
		this.xmlGarantias = xmlGarantias;
	}

}