package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesNegocio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("TotalGarantia")
	private java.lang.Double totalGarantia;
	@org.kie.api.definition.type.Label("TotalPeso")
	private java.lang.Double totalPeso;

	@org.kie.api.definition.type.Label("PrecioGramo")
	private java.lang.Double precioGramo;

	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String mensaje;

	@org.kie.api.definition.type.Label("CodigoPolitica")
	private java.lang.String codigoPolitica;

	@org.kie.api.definition.type.Label("Detener")
	private java.lang.Boolean detener;

	@org.kie.api.definition.type.Label("TotalServicios")
	private java.lang.Double totalServicios;

	@org.kie.api.definition.type.Label("PerfilInternoNuerico")
	private java.lang.Integer perfilInternoNuerico;

	@org.kie.api.definition.type.Label("DetenerColateral")
	private java.lang.Boolean detenerColateral;

	@org.kie.api.definition.type.Label(value = "DetenerColateralAdicional")
	private java.lang.Boolean detenerColateralAdicional;

	public VariablesNegocio() {
	}

	public java.lang.Double getTotalGarantia() {
		return this.totalGarantia;
	}

	public void setTotalGarantia(java.lang.Double totalGarantia) {
		this.totalGarantia = totalGarantia;
	}

	public java.lang.Double getTotalPeso() {
		return this.totalPeso;
	}

	public void setTotalPeso(java.lang.Double totalPeso) {
		this.totalPeso = totalPeso;
	}

	public java.lang.Double getPrecioGramo() {
		return this.precioGramo;
	}

	public void setPrecioGramo(java.lang.Double precioGramo) {
		this.precioGramo = precioGramo;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.String getCodigoPolitica() {
		return this.codigoPolitica;
	}

	public void setCodigoPolitica(java.lang.String codigoPolitica) {
		this.codigoPolitica = codigoPolitica;
	}

	public java.lang.Boolean getDetener() {
		return this.detener;
	}

	public void setDetener(java.lang.Boolean detener) {
		this.detener = detener;
	}

	public java.lang.Double getTotalServicios() {
		return this.totalServicios;
	}

	public void setTotalServicios(java.lang.Double totalServicios) {
		this.totalServicios = totalServicios;
	}

	public java.lang.Integer getPerfilInternoNuerico() {
		return this.perfilInternoNuerico;
	}

	public void setPerfilInternoNuerico(java.lang.Integer perfilInternoNuerico) {
		this.perfilInternoNuerico = perfilInternoNuerico;
	}

	public java.lang.Boolean getDetenerColateral() {
		return this.detenerColateral;
	}

	public void setDetenerColateral(java.lang.Boolean detenerColateral) {
		this.detenerColateral = detenerColateral;
	}

	public java.lang.Boolean getDetenerColateralAdicional() {
		return this.detenerColateralAdicional;
	}

	public void setDetenerColateralAdicional(
			java.lang.Boolean detenerColateralAdicional) {
		this.detenerColateralAdicional = detenerColateralAdicional;
	}

	public VariablesNegocio(java.lang.Double totalGarantia,
			java.lang.Double totalPeso, java.lang.Double precioGramo,
			java.lang.String mensaje, java.lang.String codigoPolitica,
			java.lang.Boolean detener, java.lang.Double totalServicios,
			java.lang.Integer perfilInternoNuerico,
			java.lang.Boolean detenerColateral,
			java.lang.Boolean detenerColateralAdicional) {
		this.totalGarantia = totalGarantia;
		this.totalPeso = totalPeso;
		this.precioGramo = precioGramo;
		this.mensaje = mensaje;
		this.codigoPolitica = codigoPolitica;
		this.detener = detener;
		this.totalServicios = totalServicios;
		this.perfilInternoNuerico = perfilInternoNuerico;
		this.detenerColateral = detenerColateral;
		this.detenerColateralAdicional = detenerColateralAdicional;
	}

}