package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesInternas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Permanencia")
	private java.lang.Integer Permanencia;
	@org.kie.api.definition.type.Label("TipoCliente")
	private java.lang.String TipoCliente;

	@org.kie.api.definition.type.Label("CarteraCliente")
	private java.lang.String CarteraCliente;

	@org.kie.api.definition.type.Label(value = "MoraPromedio")
	private java.lang.Integer moraPromedio;

	@org.kie.api.definition.type.Label(value = "MoraMaximo")
	private java.lang.Integer moraMaximo;

	@org.kie.api.definition.type.Label(value = "CantidadCreditos")
	private java.lang.Integer cantidadCreditos;

	@org.kie.api.definition.type.Label(value = "CantidadPagos")
	private java.lang.Integer cantidadPagos;

	@org.kie.api.definition.type.Label(value = "ScoreDeudor")
	private java.lang.Integer scoreDeudor;

	@org.kie.api.definition.type.Label(value = "CalificacionWebMupi")
	private java.lang.String calificacionWebMupi;

	@org.kie.api.definition.type.Label(value = "ValorOnzaTroy")
	private java.lang.Double valorOnzaTroy;

	@org.kie.api.definition.type.Label(value = "VinculadosConsepMupi")
	private java.lang.String vinculadosConsepMupi;

	@org.kie.api.definition.type.Label(value = "ImpagoQuski")
	private java.lang.String impagoQuski;

	@org.kie.api.definition.type.Label(value = "ClienteBloqueado")
	private java.lang.String clienteBloqueado;

	@org.kie.api.definition.type.Label(value = "VinculadoQuski")
	private java.lang.String vinculadoQuski;

	public VariablesInternas() {
	}

	public java.lang.Integer getPermanencia() {
		return this.Permanencia;
	}

	public void setPermanencia(java.lang.Integer Permanencia) {
		this.Permanencia = Permanencia;
	}

	public java.lang.String getTipoCliente() {
		return this.TipoCliente;
	}

	public void setTipoCliente(java.lang.String TipoCliente) {
		this.TipoCliente = TipoCliente;
	}

	public java.lang.String getCarteraCliente() {
		return this.CarteraCliente;
	}

	public void setCarteraCliente(java.lang.String CarteraCliente) {
		this.CarteraCliente = CarteraCliente;
	}

	public java.lang.Integer getMoraPromedio() {
		return this.moraPromedio;
	}

	public void setMoraPromedio(java.lang.Integer moraPromedio) {
		this.moraPromedio = moraPromedio;
	}

	public java.lang.Integer getMoraMaximo() {
		return this.moraMaximo;
	}

	public void setMoraMaximo(java.lang.Integer moraMaximo) {
		this.moraMaximo = moraMaximo;
	}

	public java.lang.Integer getCantidadCreditos() {
		return this.cantidadCreditos;
	}

	public void setCantidadCreditos(java.lang.Integer cantidadCreditos) {
		this.cantidadCreditos = cantidadCreditos;
	}

	public java.lang.Integer getCantidadPagos() {
		return this.cantidadPagos;
	}

	public void setCantidadPagos(java.lang.Integer cantidadPagos) {
		this.cantidadPagos = cantidadPagos;
	}

	public java.lang.Integer getScoreDeudor() {
		return this.scoreDeudor;
	}

	public void setScoreDeudor(java.lang.Integer scoreDeudor) {
		this.scoreDeudor = scoreDeudor;
	}

	public java.lang.String getCalificacionWebMupi() {
		return this.calificacionWebMupi;
	}

	public void setCalificacionWebMupi(java.lang.String calificacionWebMupi) {
		this.calificacionWebMupi = calificacionWebMupi;
	}

	public java.lang.Double getValorOnzaTroy() {
		return this.valorOnzaTroy;
	}

	public void setValorOnzaTroy(java.lang.Double valorOnzaTroy) {
		this.valorOnzaTroy = valorOnzaTroy;
	}

	public java.lang.String getVinculadosConsepMupi() {
		return this.vinculadosConsepMupi;
	}

	public void setVinculadosConsepMupi(java.lang.String vinculadosConsepMupi) {
		this.vinculadosConsepMupi = vinculadosConsepMupi;
	}

	public java.lang.String getImpagoQuski() {
		return this.impagoQuski;
	}

	public void setImpagoQuski(java.lang.String impagoQuski) {
		this.impagoQuski = impagoQuski;
	}

	public java.lang.String getClienteBloqueado() {
		return this.clienteBloqueado;
	}

	public void setClienteBloqueado(java.lang.String clienteBloqueado) {
		this.clienteBloqueado = clienteBloqueado;
	}

	public java.lang.String getVinculadoQuski() {
		return this.vinculadoQuski;
	}

	public void setVinculadoQuski(java.lang.String vinculadoQuski) {
		this.vinculadoQuski = vinculadoQuski;
	}

	public VariablesInternas(java.lang.Integer Permanencia,
			java.lang.String TipoCliente, java.lang.String CarteraCliente,
			java.lang.Integer moraPromedio, java.lang.Integer moraMaximo,
			java.lang.Integer cantidadCreditos,
			java.lang.Integer cantidadPagos, java.lang.Integer scoreDeudor,
			java.lang.String calificacionWebMupi,
			java.lang.Double valorOnzaTroy,
			java.lang.String vinculadosConsepMupi,
			java.lang.String impagoQuski, java.lang.String clienteBloqueado,
			java.lang.String vinculadoQuski) {
		this.Permanencia = Permanencia;
		this.TipoCliente = TipoCliente;
		this.CarteraCliente = CarteraCliente;
		this.moraPromedio = moraPromedio;
		this.moraMaximo = moraMaximo;
		this.cantidadCreditos = cantidadCreditos;
		this.cantidadPagos = cantidadPagos;
		this.scoreDeudor = scoreDeudor;
		this.calificacionWebMupi = calificacionWebMupi;
		this.valorOnzaTroy = valorOnzaTroy;
		this.vinculadosConsepMupi = vinculadosConsepMupi;
		this.impagoQuski = impagoQuski;
		this.clienteBloqueado = clienteBloqueado;
		this.vinculadoQuski = vinculadoQuski;
	}

}