package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlDescuentosNuevaOperacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "DescuentosOperacion")
	private com.relative.pruebas.DescuentosOperacion DescuentosOperacion;

	public XmlDescuentosNuevaOperacion() {
	}

	public com.relative.pruebas.DescuentosOperacion getDescuentosOperacion() {
		return this.DescuentosOperacion;
	}

	public void setDescuentosOperacion(
			com.relative.pruebas.DescuentosOperacion descuentosOperacion) {
		this.DescuentosOperacion = descuentosOperacion;
	}

	public XmlDescuentosNuevaOperacion(
			com.relative.pruebas.DescuentosOperacion descuentosOperacion) {
		this.DescuentosOperacion = descuentosOperacion;
	}

}