package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlGarantias implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Garantias")
	private com.relative.pruebas.Garantias Garantias;

	public XmlGarantias() {
	}

	public com.relative.pruebas.Garantias getGarantias() {
		return this.Garantias;
	}

	public void setGarantias(com.relative.pruebas.Garantias garantias) {
		this.Garantias = garantias;
	}

	public XmlGarantias(com.relative.pruebas.Garantias garantias) {
		this.Garantias = garantias;
	}

}