package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlParametrosRiesgo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ParametrosRiesgo")
	private com.relative.pruebas.ParametrosRiesgo ParametrosRiesgo;

	public XmlParametrosRiesgo() {
	}

	public com.relative.pruebas.ParametrosRiesgo getParametrosRiesgo() {
		return this.ParametrosRiesgo;
	}

	public void setParametrosRiesgo(
			com.relative.pruebas.ParametrosRiesgo parametrosRiesgo) {
		this.ParametrosRiesgo = parametrosRiesgo;
	}

	public XmlParametrosRiesgo(
			com.relative.pruebas.ParametrosRiesgo parametrosRiesgo) {
		this.ParametrosRiesgo = parametrosRiesgo;
	}

}