package com.relative.pruebas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlVariablesInternas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "VariablesInternas")
	private com.relative.pruebas.VariablesInternas variablesInternas;

	public XmlVariablesInternas() {
	}

	public com.relative.pruebas.VariablesInternas getVariablesInternas() {
		return this.variablesInternas;
	}

	public void setVariablesInternas(
			com.relative.pruebas.VariablesInternas variablesInternas) {
		this.variablesInternas = variablesInternas;
	}

	public XmlVariablesInternas(
			com.relative.pruebas.VariablesInternas variablesInternas) {
		this.variablesInternas = variablesInternas;
	}

}